Server_Side/smartCM/detection/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('camera/',views.livefeed, name="camera"),
    path('alert/<uuid:pk>/',views.alert, name='alert'),
    path('register/', views.registerPage, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),

    path('reset_password/',
        auth_views.PasswordResetView.as_view(template_name="detection/password_reset.html"),
        name="reset_password"),

    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name="detection/password_reset_sent.html"), 
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name="detection/password_reset_form.html"), 
        name="password_reset_confirm"),

    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name="detection/password_reset_done.html"), 
        name="password_reset_complete"),
]

Server_Side/smartCM/smartCM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('detection.urls')),
    url(r'^api/', include(('alertupload_rest.urls', 'alertupload_rest'), namespace='api')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Server_Side/smartCM/detection/models.py
import os
import uuid
from django.db import models

from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token

from django.contrib.auth.models import User

# Changes uploaded file name
def scramble_uploaded_filename(instance, filename):
    """
    Scramble / uglify the filename of the uploaded file, but keep the files extension (e.g., .jpg or .png)
    :param instance:
    :param filename:
    :return:
    """
    extension = filename.split(".")[-1]
    return "{}.{}".format(uuid.uuid4(), extension)

# Data model
class UploadAlert(models.Model):
    image = models.ImageField("Uploaded image", upload_to=scramble_uploaded_filename)
    user_ID = models.ForeignKey(Token, on_delete=models.CASCADE)
    alert_receiver = models.CharField(max_length=200)
    location = models.CharField(max_length=200)
    date_created = models.DateTimeField(auto_now_add=True)

# Generate and save a token each time a user is saved in a database
@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

Server_Side/smartCM/detection/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

# User registration form
class CreateUserForm(UserCreationForm):

	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

	# Checks if the provided email exists
	def clean_email(self):
		if User.objects.filter(email=self.cleaned_data['email']).exists():
			raise forms.ValidationError("The given email is already registered.")
		return self.cleaned_data['email']

Server_Side/smartCM/detection/views.py
from cProfile import label
from calendar import month
from django.http.response import StreamingHttpResponse
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.core.mail import EmailMessage
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

from django.views.decorators import gzip

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

import cv2

import threading

from .forms import CreateUserForm

from .filters import DetectionFilter

from .models import UploadAlert

from rest_framework.authtoken.models import Token

from django.contrib.auth import get_user_model

from django.db.models import Count

from django.db.models.functions import ExtractDay

import datetime

import itertools



# Handles the registration page
def registerPage(request):

	if request.user.is_authenticated:
		return redirect('home')
	else:
		form = CreateUserForm()
		if request.method == 'POST':
			form = CreateUserForm(request.POST)
			if form.is_valid():
				form.save()
				user = form.cleaned_data.get('username')
				messages.success(request, 'Account was successfully created for ' + user)

				return redirect('login')

		context = {'form':form}
		return render(request, 'detection/register.html', context)

# Handles the login page
def loginPage(request):
	if request.user.is_authenticated:
		return redirect('home')
	else:
		if request.method == 'POST':
			username = request.POST.get('username')
			password =request.POST.get('password')

			user = authenticate(request, username=username, password=password)

			if user is not None:
				login(request, user) 
				return redirect('home')
			else:
				messages.info(request, 'Username OR password is incorrect')

		context = {}
		return render(request, 'detection/login.html', context)

# Handles the logout
def logoutUser(request):
	logout(request)
	return redirect('login')

# Handles the dashboard page
@login_required(login_url='login')
def home(request):

	year = datetime.datetime.now().year
	month = datetime.datetime.now().month

	token = Token.objects.get(user=request.user)

	uploadAlert = UploadAlert.objects.filter(user_ID = token).order_by('-id')

	page_num  = request.GET.get('page',1)

	paginator = Paginator(uploadAlert,4)

	no_alerts = UploadAlert.objects.count()

	user = get_user_model()


	users = user.objects.all().count()

	pie_label = ['Detections','Alerts']
	pie_data = [no_alerts,no_alerts]

	myFilter = DetectionFilter(request.GET, queryset=uploadAlert)
	uploadAlert = myFilter.qs 

	# qsty = UploadAlert.objects.filter('date_created')

	# qst = UploadAlert.objects.values('date_created').annotate(count=Count('pk'))

	qst = UploadAlert.objects.values('date_created')

	var2 = itertools.groupby(qst,lambda x : x.get('date_created').strftime('%d  %B'))

	day_month = [(a,len(list(b))) for a,b in var2 ]

	print(day_month)

	label = []
	data = []

	counter = 0

	for k, v in day_month:

		if counter <= 7:
			label.append(k)
			data.append(v)
			counter = counter + 1
		else:
			break





	print(label)
	print(data)

	

	try:
		page_obj = paginator.page(page_num)

	except PageNotAnInteger:
		page_obj = paginator.page(1)
	except EmptyPage:
		page_obj = paginator.page(paginator.num_pages)

	context = {'myFilter':myFilter, 'uploadAlert':uploadAlert,'no_alerts':no_alerts, 'users':users, 'page_obj': page_obj, 'day_month':day_month,'data':data,'label':label,'pie_label':pie_label,'pie_data':pie_data}

	return render(request, 'detection/dashboard.html', context)



class VideoCamera(object):
    def __init__(self):
        self.video = cv2.VideoCapture(0)
        (self.grabbed, self.frame) = self.video.read()
        threading.Thread(target=self.update, args=()).start()

    def __del__(self):
        self.video.release()

    def get_frame(self):
        image = self.frame
        _, jpeg = cv2.imencode('.jpg', image)
        return jpeg.tobytes()

    def update(self):
        while True:
            (self.grabbed, self.frame) = self.video.read()


def gen(camera):
    while True:
        frame = camera.get_frame()
        yield(b'--frame\r\n'
            b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')


@gzip.gzip_page
def livefeed(request):
		try:
			cam = VideoCamera()
			return StreamingHttpResponse(gen(cam), content_type="multipart/x-mixed-replace;boundary=frame")
		except Exception as e: 
			print(e)
		return render(request, 'detection/cam.html')


def alert(request, pk):

	uploadAlert = UploadAlert.objects.filter(image = str(pk) + ".jpg")

	myFilter = DetectionFilter(request.GET, queryset=uploadAlert)
	uploadAlert = myFilter.qs 

	context = {'myFilter':myFilter, 'uploadAlert':uploadAlert}

	return render(request, 'detection/alert.html', context)

Server_Side/smartCM/detection/templates/detection/alert.html
{%  extends 'detection/main.html' %}
{% block content %}
{% load static %}
{% load event_tags %}

<div class="image-wrapper">
	<div class="image-cont">
		{% for alert in uploadAlert %}

		<img src="{{alert.image.url}}" alt="" class="img-fluid">

		{%endfor%}
	</div>
	<div class="about_det">

			<table class="table table-borderless">
				<tr>
					<th scope="col" class="top-row">Location</th>
					<th scope="col" class="top-row">Alert was sent to</th>
					<th scope="col" class="top-row">Time</th>
					<th scope="col" class="top-row">Camera</th>
				</tr>

				{% for alert in uploadAlert %}

				<tr>
					<td>{{alert.location}}</td>
					<td>{{alert.alert_receiver}}</td>
					<td>{{alert.date_created|date:"Y-m-d H:i:s"}}</td>
					<td ><a class="btn btn-sm btn-infor" style="background-color: #B9C488; " href="{% url 'camera' %}">Start camera</a></td> 
					
				</tr>
				{% endfor %}

			</table>
	</div>

</div>

{% endblock content%}

Server_Side/smartCM/detection/templates/detection/dashboard.html
{%  extends 'detection/main.html' %}

{% block content %}

{% load static %}

{% load event_tags %}

<div class="row body_overflow">

    <div class="limiter-form col-2 m-r-70" >      

			<form method="get">
                <h4 class="Filt-title" style="color: #fff; margin-bottom:20px; text-align: center;">Filter</h4>
				<div class="">

					<div class="">
						<!-- Location Input -->
						<input class="form-control form-input" type="text"  placeholder="Location"
						name="{{ myFilter.form.location.name }}"
						id="{{ myFilter.form.location.id_for_label }}"
						{% if myFilter.form.location.value != None %}value="{{ myFilter.form.location.value|stringformat:'s' }}"{% endif %}
						maxlength="{{ myFilter.form.location.field.max_length }}"
						{% if myFilter.form.location.field.required %}required{% endif %}>
					</div>

					<div class="">
						<!-- Alert was sent to Input -->
						<input class="form-control form-input" type="text"  placeholder="Alert was sent to"
						name="{{ myFilter.form.alert_receiver.name }}"
						id="{{ myFilter.form.alert_receiver.id_for_label }}"
						{% if myFilter.form.alert_receiver.value != None %}value="{{ myFilter.form.alert_receiver.value|stringformat:'s' }}"{% endif %}
						maxlength="{{ myFilter.form.alert_receiver.field.max_length }}"
						{% if myFilter.form.alert_receiver.field.required %}required{% endif %}>
					</div>

					<div class="">
						<!-- Start Date Input -->
						<input class="form-control form-input" type="text" id="date" placeholder="Start Date" autocomplete="off"
						name="{{ myFilter.form.start_date.name }}"
						id="{{ myFilter.form.start_date.id_for_label }}"
						{% if myFilter.form.start_date.value != None %}value="{{ myFilter.form.start_date.value|stringformat:'s' }}"{% endif %}
						maxlength="{{ myFilter.form.start_date.field.max_length }}"
						{% if myFilter.form.start_date.field.required %}required{% endif %}>
					</div>

					<div class="">
						<!-- End Date Input Input -->
						<input class="form-control form-input" type="text" id="date" placeholder="End Date" autocomplete="off"
						name="{{ myFilter.form.end_date.name }}"
						id="{{ myFilter.form.end_date.id_for_label }}"
						{% if myFilter.form.end_date.value != None %}value="{{ myFilter.form.end_date.value|stringformat:'s' }}"{% endif %}
						maxlength="{{ myFilter.form.end_date.field.max_length }}"
						{% if myFilter.form.end_date.field.required %}required{% endif %}>
					</div>

					<div class="">
						<button class="btn bt-sub" type="submit">Search</button>
					</div>

					<div class="log-out">

	

						<a class="hello-msg" href="{% url 'logout' %}" style="color: #FDFDFD; ;"><i class='bx bx-exit'></i></a>
					</div>
				</div>
			</form>
		
		


</div>

   <script>
	jQuery(document).ready(function($){
	  var date_input=$('input[id="date"]');
	  var container=$('.bootstrap-iso form').length>0 ? $('.bootstrap-iso form').parent() : "body";
	  var options={
		format: 'yyyy-mm-dd',
		container: container,
		todayHighlight: true,
		autoclose: true,
	  };
	  date_input.datepicker(options);
	});
	</script>
	
<div class=" col-9 p-t-35">

    <h2 class="m-title">Dashboard</h2>
	<h3 class="sub-t">Here are the current detections</h3>
    <div class="overview d-flex justify-content-between p-0">
        <div class="detections ">
			<div class="alert d-flex justify-content-between align-items-center">
				 <h2>Total Alerts</h2>
				  <div class="icon">
                <i class='bx bx-bell'></i>

            </div>
			</div>
           
            <h3>{{no_alerts}}</h3>

			<div class="inc d-flex justify-content-between">
				<div class="icon2"><i class='bx bxs-chevrons-up'></i></div>
				<h4><span>10%</span> +24 this week</h4>
				
			</div>
           
        </div>

		    <div class="detections ">
			<div class="alert d-flex justify-content-between">
				 <h2>Total Users</h2>
				  <div class="icon">
                <i class='bx bx-male-female'></i>
            </div>
			</div>
           
            <h3>{{users}}</h3>

			<div class="inc d-flex justify-content-between">
				<div class="icon2"><i class='bx bxs-chevrons-up'></i></div>
				<h4><span>1%</span> +1 this week</h4>
				
			</div>

        </div>


		<div class="detections ">
			<div class="alert d-flex justify-content-between">
				 <h2>Total Detections</h2>
				  <div class="icon">
                <i class='bx bx-bullseye'></i>

            </div>
			</div>
           
            <h3>{{no_alerts}}</h3>

			<div class="inc d-flex justify-content-between">
				<div class="icon2"><i class='bx bxs-chevrons-up'></i></div>
				<h4><span>10%</span> +24 this week</h4>
				
			</div>

        </div>

    </div>

	<div class="data_visualization" style="display: flex; justify-content:space-between">
		<div class="graph" style="width: 65%; background: #1D1D1D; padding: 16px;">
		<h2 style="color:#FDFDFD; font-size: 16px; font-weight: 700;">Detections against days</h2>
				<script src="https://cdn.jsdelivr.net/npm/chart.js@3.9.1/dist/chart.min.js"></script>
				<canvas id="myChart" ></canvas>
		<!-- <script src="https://cdn.jsdelivr.net/npm/chart.js"></script> -->
						<script>
						const ctx = document.getElementById('myChart').getContext('2d');
						const myChart = new Chart(ctx, {
							type: 'line',
							data: {
								labels : [{% for item in label %}"{{ item }}",{% endfor %}],
								datasets: [{
									label: "Detections",
									data : [{% for item in data %}{{ item }},{% endfor %}],
									fill : 'false',
									borderColor: '#B9C488',
									pointBackgroundColor: '#C47362',
									tension: 0.1
								}]
							},
							options: {
			animations: {
			tension: {
				duration: 1000,
				easing: 'linear',
				from: 1,
				to: 0,
				loop: true
			}
			},
			scales: {
			y: { // defining min and max so hiding the dataset does not change scale range
				min: 0,
				max: 100
			}
			}
		}
						});
						
						</script>
		
	</div>
	<div class="pie" style="max-width: 30%; max-height: 55vh;  background: #1D1D1D; padding: 16px;">
		<h2 style="color:#FDFDFD; font-size: 16px; font-weight: 700;">Detections Vs Alerts</h2>
				<script src="https://cdn.jsdelivr.net/npm/chart.js@3.9.1/dist/chart.min.js"></script>
				<canvas id="myChart2" ></canvas>
		<!-- <script src="https://cdn.jsdelivr.net/npm/chart.js"></script> -->
						<script>
						const ctx2 = document.getElementById('myChart2').getContext('2d');
						const myChart2 = new Chart(ctx2, {
							type: 'doughnut',
							data: {
								labels : [{% for item in pie_label %}"{{ item }}",{% endfor %}],
								datasets: [{
									label: "Detections vs Alerts",
									data : [{% for item in pie_data %}{{ item }},{% endfor %}],
									borderColor: '#242424',
									backgroundColor: ['#D0F266','#E1502E'],
									hoverOffset: 4
									
								}]
							},
							
						
						});
						
						</script>
		


	</div>
	</div>

    <div class="limiter-data">
		
        		<table class="table table-image table-borderless ">
				<tr>
					<th scope="col" class="top-row">Snippet</th> 
					<th scope="col" class="top-row">Location</th> 
					<th scope="col" class="top-row">Alert was sent to</th>
					<th scope="col" class="top-row">Time</th>
					<th scope="col" class="top-row">Alert</th> 
				</tr>


				{% for alert in page_obj %}

				<tr   >
					<td class="w-25"><img style="width: 100px; height: 60px; border-radius: 3px; border: 2px solid #B9C488;" 
						class="img-fluid" src="{{alert.image.url}}"/></td>
					<td>{{alert.location}}</td>
					<td>{{alert.alert_receiver}}</td>
					<td>{{alert.date_created|date:"Y-m-d H:i:s"}}</td>
					
					{% with uuid=alert.image|split:"." %}

					<td><a class="btn btn-sm btn-infor" style="color: #B9C488; " href="/alert/{{uuid.0}}/">View</a></td>

					{% endwith %}
					
				</tr>

				{% endfor %}

				
				<br>

			</table>

	

			
				<div>

					<span class="pg-control">
						{% if page_obj.has_previous %}
						<a href="?page={{ page_obj.previous_page_number }}">Previous</a>
						{% endif %}
						<span>
						Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
						</span>
						{% if page_obj.has_next %}
						<a href="?page={{ page_obj.next_page_number }}">Next</a>
						{% endif %}
					</span>
					
				</div>
		
    </div>

	
		


</div>

	
</div>


{% endblock %}

Server_Side/smartCM/detection/templates/detection/login.html
{% load static %}

<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static '/css/login.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/util.css' %}">


</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-50">
				<form class="login100-form validate-form" method="POST" action="">
					{% csrf_token %}
					<span class="login100-form-title p-b-33">
						Account Login
					</span>

					<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						<input class="input100" type="text" name="username" placeholder="Username">
					</div>

					<div class="wrap-input100 rs1 validate-input" data-validate="Password is required">
						<input class="input100" type="password" name="password" placeholder="Password">
					</div>

					<div class="container-login100-form-btn m-t-20 m-b-15">
						<button class="login100-form-btn" type="submit" value="Login">
							Sign in
						</button>
					</div>

					{% for message in messages %}
					<p id="messages">{{message}}</p>
					{% endfor %}	

					<div class="text-center p-t-15 p-b-4">
						<span class="txt1">
							Forgot
						</span>

						<a href="{% url 'reset_password' %}" class="txt2 hov1">
							Password?
						</a>
					</div>

					<div class="text-center">
						<span class="txt1">
							Create an account?
						</span>

						<a href="{% url 'register' %}" class="txt2 hov1">
							Sign up
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>

</body>

</html>

Server_Side/smartCM/detection/templates/detection/main.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>Smart Camera Manager</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{% static '/css/dashboard.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/util.css' %}">
	<link rel="stylesheet" href="{% static '/css/alert.css' %}">

	<!--  jQuery -->
	<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>

	<!-- Bootstrap Date-Picker Plugin -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>
	<link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>
	
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>

	<script src="https://cdn.jsdelivr.net/npm/chart.js@3.9.1/dist/chart.min.js"></script>

</head>
<body>
	{%  include 'detection/navbar.html' %}

	<div class="container-fluid ">

	{% block content %}

	{% endblock %}
    </div>
	
</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

Server_Side/smartCM/detection/templates/detection/navbar.html
  
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static '/css/navbar.css' %}">
<link rel="stylesheet" type="text/css" href="{% static '/css/util.css' %}">

<nav class="navbar navbar-dark  justify-content-between nav-back" style="border-bottom: 0.5px solid #282828;">
    <span class="navbar-brand" style=" color: #FDFDFD; font-weight: 900;">Weapon Detection</span>

    <ul class="form-inline my-2 my-lg-0">
      <span class="hello-msg" style="color: #FDFDFD;ss ; font-weight: 900;">Welcome back, {{request.user}}</span>
      <span ><a class="hello-msg" href="{% url 'logout' %}" style="color: #FDFDFD; ;">Logout</a></span>
    </ul>

  
  </nav>

Server_Side/smartCM/detection/templates/detection/password_reset.html
{% load static %}

<!DOCTYPE html>
<html>
    
<head>
	<title>Reset Password</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static '/css/login.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/util.css' %}">


</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-50">
				<form class="login100-form validate-form" method="POST" action="">
					{% csrf_token %}
					<span class="login100-form-title p-b-20">
						Password Reset
					</span>

					<div class="text-center p-b-4">
						<p style="color: #555555;">
							Forgotten your password?
						</p>
						<p class="p-t-15 p-b-25">
							Enter your email address below, and we’ll email instructions for setting a new one.
						</p>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						<input class="input100" type="email" name="email" autocomplete="email" placeholder="Email" id="id_email">
					</div>

					<div class="container-login100-form-btn m-t-20 m-b-15">
						<button class="login100-form-btn" type="submit" value="Send email">
							Submit
						</button>
					</div>
						
					<div class="text-center p-t-15">
						<span class="txt1">
							Remember your password?
						</span>

						<a href="{% url 'login' %}" class="txt2 hov1">
							Login
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>

</body>

</html>

Server_Side/smartCM/detection/templates/detection/password_reset_done.html
  
{% load static %}

<!DOCTYPE html>
<html>
    
<head>
	<title>Password Changed</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static '/css/login.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/util.css' %}">


</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-50">

					<span class="login100-form-title p-b-15">
						Password Reset Complete
					</span>

					<div class="text-center p-b-4">

						<p class="p-b-4">
							Your password has been set.
						</p>
						<p>
							You may go ahead and 
							<a href="{% url 'login' %}" class="txt2 hov1">
								Login
							</a>
							now.
						</p>

					</div>
			</div>
		</div>
	</div>

</body>

</html>